#!/usr/bin/env python3
"""
Generate a C header of composite KEM known-answer vectors.

Reads the LAMPS working group's testvectors.json and emits base64 string
literals, one struct per test case.  Base64 rather than hex because that is
how the source file stores them: re-encoding here would mean this script and
the C decoder could disagree about a vector without anything failing loudly.

The header carries no JSON parser and no runtime file access, so the KAT
binary depends only on the C library and OpenSSL.

Usage:
    gen_kem_vectors.py <testvectors.json> <output.h>
"""

import json
import os
import sys
import textwrap

# These are the short names the provider registers, copied from
# src/common/composite_provider.h.  The generated tc_id is fed straight to
# EVP_PKEY_CTX_new_from_name(), so it has to be the provider's spelling.
#
# Verified against lamps-wg/draft-composite-kem@d77e754 (2026-08-07): the
# file's tcId values use exactly these spellings.  If a future revision
# renames them (the draft has used "-HMAC-SHA256" / "-HMAC-SHA512" for the
# RSA and ECDH combinations at various points), this script stops and prints
# what it did find; reconcile the two before trusting any KAT result, because
# a mismatch here means testing the wrong algorithm, not just a failed lookup.
EXPECTED_ALGORITHMS = [
    "id-MLKEM768-RSA2048-SHA3-256",
    "id-MLKEM768-RSA3072-SHA3-256",
    "id-MLKEM768-RSA4096-SHA3-256",
    "id-MLKEM768-X25519-SHA3-256",
    "id-MLKEM768-ECDH-P256-SHA3-256",
    "id-MLKEM768-ECDH-P384-SHA3-256",
    "id-MLKEM768-ECDH-brainpoolP256r1-SHA3-256",
    "id-MLKEM1024-RSA3072-SHA3-256",
    "id-MLKEM1024-ECDH-P384-SHA3-256",
    "id-MLKEM1024-ECDH-brainpoolP384r1-SHA3-256",
    "id-MLKEM1024-X448-SHA3-256",
    "id-MLKEM1024-ECDH-P521-SHA3-256",
]

# Fields taken from each test case.  dk_pkcs8 and x5c are optional: Phase 7/8
# need them, Phases 3-6 do not, and an older vector file may predate them.
REQUIRED_FIELDS = ["dk", "ek", "c", "k"]
OPTIONAL_FIELDS = ["dk_pkcs8", "x5c"]


def c_string_literal(value, indent):
    """Emit a base64 blob as adjacent C string literals, wrapped for width."""
    if not value:
        return "NULL"
    chunks = textwrap.wrap(value, 72)
    pad = " " * indent
    return ("\n" + pad).join('"%s"' % chunk for chunk in chunks)


def load_cases(path):
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)

    # The file has been both a bare list and an object wrapping one; accept
    # either rather than breaking on a cosmetic upstream change.
    if isinstance(data, dict):
        for key in ("tests", "testVectors", "vectors"):
            if key in data:
                data = data[key]
                break
    if not isinstance(data, list):
        raise SystemExit("unexpected JSON layout: expected a list of test cases")

    by_id = {}
    for case in data:
        tc_id = case.get("tcId") or case.get("name")
        if tc_id is None:
            raise SystemExit("test case with no tcId")
        by_id[tc_id] = case
    return by_id


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__.strip())

    src, dst = sys.argv[1], sys.argv[2]
    by_id = load_cases(src)

    missing = [a for a in EXPECTED_ALGORITHMS if a not in by_id]
    if missing:
        raise SystemExit(
            "vector file is missing %d expected algorithm(s):\n  %s\n\n"
            "tcId values actually present in %s:\n  %s\n\n"
            "If the draft renamed these, update EXPECTED_ALGORITHMS at the top "
            "of this script (and the tc_id -> provider name mapping in "
            "test_kem_decaps_vectors.c) to match."
            % (
                len(missing),
                "\n  ".join(missing),
                os.path.basename(src),
                "\n  ".join(sorted(by_id)) or "(none)",
            )
        )

    out = []
    out.append("/*")
    out.append(" * Generated by tests/tools/gen_kem_vectors.py -- do not edit.")
    out.append(" *")
    out.append(" * Source: %s" % os.path.basename(src))
    out.append(" * Values are base64, exactly as they appear in the source file.")
    out.append(" */")
    out.append("")
    out.append("#ifndef COMPOSITE_KEM_TEST_VECTORS_H")
    out.append("#define COMPOSITE_KEM_TEST_VECTORS_H")
    out.append("")
    out.append("/* The base64 blobs exceed ISO C99's 4095-byte minimum for a")
    out.append(" * string literal, which -Wpedantic warns about. */")
    out.append("#if defined(__GNUC__) || defined(__clang__)")
    out.append("#pragma GCC diagnostic push")
    out.append('#pragma GCC diagnostic ignored "-Woverlength-strings"')
    out.append("#endif")
    out.append("")
    out.append("typedef struct {")
    out.append("    const char *tc_id;      /* draft algorithm name */")
    out.append("    const char *dk;         /* raw private key, draft 4.2 */")
    out.append("    const char *dk_pkcs8;   /* PrivateKeyInfo, or NULL */")
    out.append("    const char *ek;         /* raw public key, draft 4.1 */")
    out.append("    const char *x5c;        /* DER certificate, or NULL */")
    out.append("    const char *c;          /* ciphertext */")
    out.append("    const char *k;          /* expected shared secret */")
    out.append("} COMPOSITE_KEM_TEST_VECTOR;")
    out.append("")
    out.append("static const COMPOSITE_KEM_TEST_VECTOR composite_kem_vectors[] = {")

    for tc_id in EXPECTED_ALGORITHMS:
        case = by_id[tc_id]
        for field in REQUIRED_FIELDS:
            if not case.get(field):
                raise SystemExit("%s: missing required field %r" % (tc_id, field))

        out.append("    {")
        out.append('        "%s",' % tc_id)
        for field in ["dk", "dk_pkcs8", "ek", "x5c", "c", "k"]:
            value = case.get(field) if field in REQUIRED_FIELDS + OPTIONAL_FIELDS else None
            out.append("        %s," % c_string_literal(value, 8))
        out.append("    },")

    out.append("};")
    out.append("")
    out.append("#define COMPOSITE_KEM_VECTOR_COUNT \\")
    out.append("    (sizeof(composite_kem_vectors) / sizeof(composite_kem_vectors[0]))")
    out.append("")
    out.append("#if defined(__GNUC__) || defined(__clang__)")
    out.append("#pragma GCC diagnostic pop")
    out.append("#endif")
    out.append("")
    out.append("#endif /* COMPOSITE_KEM_TEST_VECTORS_H */")

    with open(dst, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out) + "\n")

    print("wrote %s (%d vectors)" % (dst, len(EXPECTED_ALGORITHMS)))


if __name__ == "__main__":
    main()
