#!/usr/bin/env bash
# gen_composite_cms_v3.sh
#
# Generates artifacts_cms_v3.zip for the 12 composite KEM OIDs using CMS
# KEMRecipientInfo, AES-256-WRAP, and the README's MTI KDF:
# id-alg-hkdf-with-sha256.
#
# The script expects the R5 certificate artifacts to already exist in the same
# provider directory, normally generated by gen_composite_r5.sh.  It reuses the
# KEM keys but issues CMS-specific KEM EE certificates under a level-1 ML-DSA TA,
# matching the CMS v3 README shape.
#
# Usage:
#   ./scripts/gen_composite_cms_v3.sh [provider_artifact_dir]
#
# Environment variables:
#   OPENSSL_DIR   — OpenSSL build directory (default: workspace root)
#   OPENSSL_BIN   — Path to openssl binary  (default: OPENSSL_DIR/apps/openssl)
#   OPENSSL_CONF  — Path to openssl.cnf

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

OPENSSL_DIR="${OPENSSL_DIR:-${WORKSPACE_ROOT}/openssl}"
OPENSSL_BIN="${OPENSSL_BIN:-${OPENSSL_DIR}/apps/openssl}"
export LD_LIBRARY_PATH="${OPENSSL_DIR}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export OPENSSL_MODULES="${OPENSSL_MODULES:-${WORKSPACE_ROOT}/_build}"
OPENSSL_CONF="${OPENSSL_CONF:-${WORKSPACE_ROOT}/tests/composite.cnf}"
export OPENSSL_CONF

OUTPUT_DIR="${1:-${SCRIPT_DIR}}"
mkdir -p "${OUTPUT_DIR}"

COMPOSITE_KEM_ALGOS=(
    "id-MLKEM768-RSA2048-SHA3-256                       1.3.6.1.5.5.7.6.55"
    "id-MLKEM768-RSA3072-SHA3-256                       1.3.6.1.5.5.7.6.56"
    "id-MLKEM768-RSA4096-SHA3-256                       1.3.6.1.5.5.7.6.57"
    "id-MLKEM768-X25519-SHA3-256                        1.3.6.1.5.5.7.6.58"
    "id-MLKEM768-ECDH-P256-SHA3-256                     1.3.6.1.5.5.7.6.59"
    "id-MLKEM768-ECDH-P384-SHA3-256                     1.3.6.1.5.5.7.6.60"
    "id-MLKEM768-ECDH-brainpoolP256r1-SHA3-256          1.3.6.1.5.5.7.6.61"
    "id-MLKEM1024-RSA3072-SHA3-256                      1.3.6.1.5.5.7.6.62"
    "id-MLKEM1024-ECDH-P384-SHA3-256                    1.3.6.1.5.5.7.6.63"
    "id-MLKEM1024-ECDH-brainpoolP384r1-SHA3-256         1.3.6.1.5.5.7.6.64"
    "id-MLKEM1024-X448-SHA3-256                         1.3.6.1.5.5.7.6.65"
    "id-MLKEM1024-ECDH-P521-SHA3-256                    1.3.6.1.5.5.7.6.66"
)

KDF_NAME="id-alg-hkdf-with-sha256"
CMS_UKM="0102030405060708090a0b0c0d0e0f1011121314"
CMS_SIGNING_TA_OID="1.3.6.1.5.5.7.6.37"
CMS_SIGNING_TA_CERT=""
CMS_SIGNING_TA_KEY=""

PASS=0
FAIL=0
declare -a FAILURES=()

WORK_DIR="$(mktemp -d /tmp/gen_composite_cms_v3.XXXXXX)"
STAGING_PARENT="${WORK_DIR}/staging"
STAGING_DIR="${STAGING_PARENT}/artifacts_cms_v3"
mkdir -p "${STAGING_DIR}"
trap 'rm -rf "${WORK_DIR}"' EXIT

PLAINTEXT="${STAGING_DIR}/expected_plaintext.txt"
printf "Hello, World!" > "${PLAINTEXT}"

prepare_cms_ta() {
    CMS_SIGNING_TA_CERT="$(find "${OUTPUT_DIR}" -maxdepth 1 -name "*${CMS_SIGNING_TA_OID}_ta.der" 2>/dev/null | sort | head -n 1)"
    CMS_SIGNING_TA_KEY="$(find "${OUTPUT_DIR}" -maxdepth 1 -name "*${CMS_SIGNING_TA_OID}_priv.der" 2>/dev/null | sort | head -n 1)"

    if [[ -z "${CMS_SIGNING_TA_CERT}" || -z "${CMS_SIGNING_TA_KEY}" ]]; then
        echo "ERROR: required CMS signing TA/key for ${CMS_SIGNING_TA_OID} not found in ${OUTPUT_DIR}"
        return 1
    fi

    cp "${CMS_SIGNING_TA_CERT}" "${STAGING_DIR}/ta.der"
}

issue_cms_ee_cert() {
    local source_ee="$1"
    local issued_ee="$2"
    local friendly="$3"
    local pub_file="${WORK_DIR}/${friendly}.pub.pem"
    local ext_file="${WORK_DIR}/${friendly}.ext"
    local err

    err="$("${OPENSSL_BIN}" x509 -inform DER \
            -in "${source_ee}" \
            -pubkey -noout \
            -out "${pub_file}" 2>&1)"
    if [[ $? -ne 0 ]]; then
        echo "${err}" | sed 's/^/    /'
        return 1
    fi

    {
        printf "subjectKeyIdentifier=none\n"
        printf "subjectAltName=critical,DNS:%s.cms.example\n" "${friendly}"
        printf "basicConstraints=critical,CA:false\n"
        printf "keyUsage=critical,keyEncipherment\n"
    } > "${ext_file}"

    err="$("${OPENSSL_BIN}" x509 -new \
            -outform DER \
            -out "${issued_ee}" \
            -CAform DER \
            -CA "${CMS_SIGNING_TA_CERT}" \
            -CAkey "${CMS_SIGNING_TA_KEY}" \
            -CAkeyform DER \
            -force_pubkey "${pub_file}" \
            -days 3650 \
            -subj "/" \
            -extfile "${ext_file}" 2>&1)"
    if [[ $? -ne 0 ]]; then
        echo "${err}" | sed 's/^/    /'
        return 1
    fi
}

generate_cms() {
    local ee_file="$1"
    local out_file="$2"
    local cipher="$3"
    local with_ukm="$4"
    local err

    if [[ "${with_ukm}" == "yes" ]]; then
        err="$("${OPENSSL_BIN}" cms -encrypt -binary \
                -in "${PLAINTEXT}" \
                -outform DER \
                -out "${out_file}" \
                -recip "${ee_file}" \
                "${cipher}" \
                -wrap aes-256-wrap \
                -recip_kdf "${KDF_NAME}" \
                -recip_ukm "${CMS_UKM}" 2>&1)"
    else
        err="$("${OPENSSL_BIN}" cms -encrypt -binary \
                -in "${PLAINTEXT}" \
                -outform DER \
                -out "${out_file}" \
                -recip "${ee_file}" \
                "${cipher}" \
                -wrap aes-256-wrap \
                -recip_kdf "${KDF_NAME}" 2>&1)"
    fi

    if [[ $? -ne 0 ]]; then
        echo "${err}" | sed 's/^/    /'
        return 1
    fi
}

echo "Composite KEM CMS v3 Artifact Generation"
echo "========================================"
echo "OpenSSL:  ${OPENSSL_BIN}"
echo "Output:   ${OUTPUT_DIR}/artifacts_cms_v3.zip"
echo ""

if ! prepare_cms_ta; then
    exit 1
fi

for entry in "${COMPOSITE_KEM_ALGOS[@]}"; do
    read -r friendly oid <<< "${entry}"
    base="${friendly}-${oid}"
    source_ee_file="${OUTPUT_DIR}/${base}_ee.der"
    ee_file="${STAGING_DIR}/${base}_ee.der"
    priv_file="${OUTPUT_DIR}/${base}_priv.der"

    printf "  %-58s " "${friendly}"

    if [[ ! -f "${source_ee_file}" || ! -f "${priv_file}" ]]; then
        echo "FAIL (missing ee/private key)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: missing ${base}_ee.der or ${base}_priv.der")
        continue
    fi

    if ! issue_cms_ee_cert "${source_ee_file}" "${ee_file}" "${friendly}"; then
        echo "FAIL (ee cert)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: CMS EE certificate generation failed")
        continue
    fi

    cp "${priv_file}" "${STAGING_DIR}/${base}_priv.der"

    if ! generate_cms "${ee_file}" "${STAGING_DIR}/${base}_kemri_${KDF_NAME}.der" "-aes-256-cbc" "no"; then
        echo "FAIL (kemri)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: KEMRI generation failed")
        continue
    fi

    if ! generate_cms "${ee_file}" "${STAGING_DIR}/${base}_kemri_${KDF_NAME}_ukm.der" "-aes-256-cbc" "yes"; then
        echo "FAIL (kemri ukm)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: KEMRI UKM generation failed")
        continue
    fi

    if ! generate_cms "${ee_file}" "${STAGING_DIR}/${base}_kemri_ukm.der" "-aes-256-cbc" "yes"; then
        echo "FAIL (kemri ukm alias)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: KEMRI UKM alias generation failed")
        continue
    fi

    if ! generate_cms "${ee_file}" "${STAGING_DIR}/${base}_kemri_auth_${KDF_NAME}.der" "-aes-256-gcm" "no"; then
        echo "FAIL (kemri auth)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: auth KEMRI generation failed")
        continue
    fi

    if ! generate_cms "${ee_file}" "${STAGING_DIR}/${base}_kemri_auth.der" "-aes-256-gcm" "no"; then
        echo "FAIL (kemri auth alias)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: auth KEMRI alias generation failed")
        continue
    fi

    if ! generate_cms "${ee_file}" "${STAGING_DIR}/${base}_kemri_auth_${KDF_NAME}_ukm.der" "-aes-256-gcm" "yes"; then
        echo "FAIL (kemri auth ukm)"
        FAIL=$((FAIL + 1))
        FAILURES+=("${friendly}: auth KEMRI UKM generation failed")
        continue
    fi

    echo "OK"
    PASS=$((PASS + 1))
done

echo ""

ZIP_PATH="${OUTPUT_DIR}/artifacts_cms_v3.zip"
rm -f "${ZIP_PATH}"

if ! zip_err="$(cd "${STAGING_PARENT}" && zip -rqX "${ZIP_PATH}" artifacts_cms_v3 2>&1)"; then
    echo "ERROR: zip failed:"
    echo "${zip_err}" | sed 's/^/  /'
    exit 1
fi

echo "========================================"
printf "Generated: %d/%d KEM CMS artifact sets\n" "${PASS}" "$((PASS + FAIL))"

if [[ ${#FAILURES[@]} -gt 0 ]]; then
    echo ""
    echo "Failed:"
    for f in "${FAILURES[@]}"; do
        echo "  - ${f}"
    done
fi

echo ""
echo "Zip:  ${ZIP_PATH}"
echo "Size: $(du -sh "${ZIP_PATH}" | cut -f1)"
echo ""

[[ ${FAIL} -eq 0 ]]
