#ifndef _MLDSA_COMPOSITE_H
#define _MLDSA_COMPOSITE_H

#include "compat.h"
#include "composite_provider.h"

#include <openssl/core_names.h>

BEGIN_C_DECLS

                    // ==============
                    // KEM operations
                    // ==============
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_rsa2048)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_rsa3072)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_rsa4096)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_x25519)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_p256)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_p384)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem768_brainpoolp256)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024_rsa3072)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024_p384)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024_brainpoolp384)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024_x448)
EXTERN_DECLARE_KEM_DISPATCH_TABLE(mlkem1024_p521)

END_C_DECLS

#endif /* _MLDSA_COMPOSITE_H */
